# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Git-version
      run: git version
    - name: Git-remote-add
      run: git remote add adobe https://github.com/weide-zhou/aem-sync-to.git
    - name: Git-remote-v
      run: |
        git remote -v
    - name: Git-fetch-all
      run: git fetch --all    
    - name: Git-checkout-adobe
      run: git checkout -b sync-demo-master adobe/master
    - name: set
      run: |
        git config --global user.email "weide-zhou@outlook.com"
        git config --global user.name "weide-zhou"
    - name: Git-merge
      run: git merge adobe/master --allow-unrelated-histories
    - name: Git-push
      run: git push --set-upstream adobe master
